### ISSUE TITLE
Save Edits and Mobile

### ISSUE THREAD

**Issue by sentientroleplay** [pyxfluff/moderntheme#1]
The theme is fantastic and looks absolutely phenominal. There were just some minor issues I wanted to mention. 

Sometimes when making a change on the theme, the save buttons are invisible and I have to refresh a few times to get it to work for me. 😔 I'm not sure if any other buttons are affected.

Also wanted to add that it's a bit clunky on mobile unless I'm doing something wrong.

**Comment by pyxfluff** [comment]
Hi there, this repository hosts the rewrite which is still in progress, it is not finished or intended for use generally.

If you want to use the old version, please use https://github.com/pyxfluff/darkpixlz-Modern-Theme instead. Thanks!
